### ISSUE TITLE
Orlando Perrone > Wildcards

### ISSUE THREAD

**Issue by dcodeIO** [dcodeIO/___wildcards#1]
`Source: https://www.facebook.com/wildcardsgame/posts/144592245712298`

Hello.

I love your game, and I have a few suggestions if you don't mind. Thanks for creating such an awesome game of CAH. We played this at PAX East 2013 and have been frequenting it almost daily.

1.) The tone is way too loud. Very very loud. If you could please lower the volume a bit.

2.) I love the design of the whole site, but another tidbit would be how the cards scroll vertically once all are selected. If you could have them pair horizontally or just show the black cards and all the white cards in horizontal rows. Most people have widescreen monitors and scrolling down all the answers is time consuming and scroll intensive. There are usually at least 5-10 of us playing at any given time, so that much scrolling gets kind of tiring.

3.) The timer to choose is VERY fast. Sometimes I don't get to pair up my answers before the game force chooses my hand. A timer is fine, but perhaps you could have it longer, or make a group vote a skip for an AFK player.

4.) If you could put more emphasis on who is the card czar, like a notice so that the current player knows, and a different color glow around the card czar so that other players know.

Other than that, its great at the moment. My friends and I at Team9000.net are looking for a good solid build of the game and yours has the best UI at the moment. You are only topped by one that has video chat, but the minimalist design of yours is much better.

These are just suggestions, I'm not telling you what to do, please consider them and keep up the awesome work.

**Comment by dcodeIO** [comment]
Orlando, I appreciate your feedback. Regarding your points and the current design:

1) I do not have some really catchy sounds currently, so I took the current ones mostly as a placeholder. I'll look into that.

2) The design is based on the decision to make the game work cross-platform, even on mobile phones. However, it would be possible to alter the layout for high resolutions, e.g. full HD, to use a different approach of displaying selection results. At 1920px width and with 200px cards width this would make up ~9 colums (requires exactly 1800px width of the browser window), so it should work as there are 8 selections max. plus one colum that might be used for the black card or just reserved.

3) Currently the timer is set to 30 seconds, which is quite fast. I tested the game with only a few players till now. It might be an option to make it adapt to the actual number of players, let's say beginning at 30 seconds for 2 players and ending at 60 seconds for 9 players or something. However, marking a player as AFK might - or might not - result in unfair use of that tool. What would you suggest?

4) Yes, I will change that.

Feel free to answer at GitHub or, if you do not want to register at GH, you can just answer at Facebook.

**Comment by JerzeyLegend** [comment]
1.) Appreciate it. We use the game over mumble and most of use headsets, so the sounds are BLASTED into our ears. :+1: 

2.) I did not know it works on mobile phones. I am now interested in trying this on a tablet. :) Sure, 9 columns across with 1 being reserved for the black card and starting a new row for any cards beyond that is fine. I mean in the end, you need it to make work best for multiple resolutions, platforms, etc. Just food for thought. A group of 5 of us played last night and that was our first concern: scrolling.

3.) 30 seconds is very fast in a group of 5. People need time to think it through, might get distracted, etc. I think 45-60 would be more fair, with a popup timer? Is it also possible to have a pass button? Also could you make it so the game does not force a card?  If a player does not go, the player does not get a point, and don't allow them to get a new card, so really, no advantage is had. Just suggestions.

4.) :+1: 

Thanks for considering my feedback. Gonna point my friends here in case they have any feedback.

**Comment by dcodeIO** [comment]
Just deployed:

1) Changed the nudge sound to something comfortable.

3) Dynamic timer from 30 to 60 seconds depending on number of players, plus timer value display. Please try it out and let me know if the values need additional adjustment.

4) Highlighted the card czar in black.

**Comment by JerzeyLegend** [comment]
It was all great, thanks.
